# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "9:00"
      timezone: "Europe/Rome"
    assignees:
      - "AstralJaeger"
    commit-message:
        prefix: "pip"
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    labels:
      - "pip"
      - "dependencies"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "9:00"
      timezone: "Europe/Rome"
    assignees:
      - "AstralJaeger"
    commit-message:
      prefix: "pip"
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    labels:
      - "docker"
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "9:00"
      timezone: "Europe/Rome"
    assignees:
      - "AstralJaeger"
    commit-message:
      prefix: "actions"
    open-pull-requests-limit: 5
    labels:
      - "actions"
      - "dependencies"